### ISSUE TITLE
Pairing \( ... \) and \[ ... \]?

### ISSUE THREAD

**Issue by gertekoo** [rzukic/zed-latex#42]
These two useful and common pairings , for inline math instead of $ ... $, and for display math, seem to be missing. It could be useful to have typing the opening character sequence immediately trigger displaying the closing sequence and positioning the cursor in between the opening and closing sequences.

**Comment by lnay** [comment]
I tried including those before but there didn't seem to be an order which avoided conflicts between the different auto-pair completions.
Maybe they could be added if Zed's behaviour has changed. However I believe `texlab` provides a snippet for those.

**Comment by lnay** [comment]
If you can find a suitable edit to [languages/latex/config.toml] that works well, please share the diff or submit a PR. But I think the "shorter" paired items should be prioritized as they don't have snippets.

**Comment by lnay** [comment]
Closed by #46
