### ISSUE TITLE
latexmk with --lualatex and --shell-escape options

### ISSUE THREAD

**Issue by Martin-2019** [rzukic/zed-latex#49]
Dear Author!

How to configure Zed-LaTeX to compile with latexmk and lualatex as engine as well as --shell-escape enable?

In my settings I wrote:

```jsonc
// Zed settings
//
// For information on how to configure Zed, see the Zed
// documentation: https://zed.dev/docs/configuring-zed
//
// To see all of Zed's default settings without changing your
// custom settings, run `zed: open default settings` from the
// command palette (cmd-shift-p / ctrl-shift-p)
{
  "ui_font_size": 16,
  "buffer_font_size": 16,
  "theme": {
    "mode": "system",
    "light": "Tokyo Night Light",
    "dark": "One Dark"
  },
  "lsp": {
    "texlab": {
      "settings": {
        "texlab": {
          "build": {
            "onSave": true,
            //"executable": "latexmk",
            //"args": [
            //  "--shell-escape",
            //  "--lualatex",
            //  "--synctex=1",
            // "%f",
            //],
            "forwardSearchAfter": true
          },
          "forwardSearch": {
            "executable": "/Applications/Skim.app/Contents/SharedSupport/displayline",
            "args": ["-r", "%l", "%p", "%f"]
          }
        }
      }
    }
  }
}
```

but it does not work?

Thank You in advance!

**Comment by lnay** [comment]
Are those lines in the settings with "lualatex" and "shell-escape" indeed commented out?

An alternative is to consider is to specify these things in a latexmkrc file in the project.

**Comment by Martin-2019** [comment]
Yes?

**Comment by lnay** [comment]
> Yes?
I apologize if I am misunderstanding, but have you tried removing the "//" at the beginning of the lines in the block in the middle (starting with "executable")?

**Comment by Martin-2019** [comment]
No? I am interesting with configurations, but I am not programmer, unfortunately...

**Comment by lnay** [comment]
My recommendation is to put the following contents in a file (name it "latexmkrc") into your project:
```perl
$pdflatex = 'lualatex %O %S --shell-escape';
$pdf = 1;
```

This will keep this configuration specific to the one project. It will also work whenever you run `latexmk` in the folder, whether it is run by `texlab`, or you decide to use the "play button" in the editor (which runs a Zed "task").

**Comment by Martin-2019** [comment]
Thank You
