### ISSUE TITLE
\begin{} enviroment function completion lacking backslash in end

### ISSUE THREAD

**Issue by ivansigmund** [rzukic/zed-latex#5]
what i get  when i start writing \begin{} in zed, notice there is no backslash before end: 

https://github.com/user-attachments/assets/2726cad2-f981-42ff-acaf-0a8d3d681410

what i expect is that the completion works like in neovim, at least that there is a beckslash:

https://github.com/user-attachments/assets/3e5d3ff9-39cb-4d3f-a45d-6fa764d51cf2

i tried using the snippets extension, it as well has a backslash problem, i.e. it does not write backslashes. as i wrote [here]( https://github.com/zed-industries/zed/issues/4611#issuecomment-2191526559).

**Comment by lnay** [comment]
Possible [culprit](https://github.com/zed-industries/zed/blob/a072caab0b22b102f2be73189b1b5cd14eee5ae6/crates/snippet/src/snippet.rs#L51)

**Comment by lnay** [comment]
Should be sorted in next Zed release

**Comment by lnay** [comment]
The fix came through in Zed version [0.146.3](https://zed.dev/releases/stable/0.146.3)
