### ISSUE TITLE
Improve `%` behavior for navigating `\begin` and `\end` blocks

### ISSUE THREAD

**Issue by domi413** [rzukic/zed-latex#50]
When using the Zed-LaTeX plugin, pressing `%` while on a `\end{...}` jumps to the corresponding opening bracket of the `\begin{...}`, rather than directly to the `\begin` statement itself. The same happens in reverse when pressing `%` on a `\begin`.  (Except if the cursor is under the `\` ...)

For example:  
- In Neovim + TexLab, pressing `%` on `\end{...}` jumps directly to `\begin{...}`, and vice versa.  
- In Zed, pressing `%` on `\end{...}` instead jumps to the `{...}` brackets of the `\begin`, which makes navigation less intuitive.

**Comment by lnay** [comment]
That's a Zed issue really. It will jump between the `\begin` and `\end` successfully but only if the cursor is at the beginning of either one (on the `\`).

I agree that this behaviour is not consistent with vim/nvim+extra.

**Comment by lnay** [comment]
Presumably they had an oversight expecting "brackets" to only be one character long.

**Comment by domi413** [comment]
So... should I rather open an issue in zed?

**Comment by lnay** [comment]
Yeah, and check whether there is an existing issue.
